"""initial

Revision ID: 8a3fb0b0b01a
Revises:
Create Date: 2026-03-16 01:55:03.620405

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3fb0b0b01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    propertytype = sa.Enum("LAND", "HOUSE", "APARTMENT", "COMMERCIAL", name="propertytype")
    propertystatus = sa.Enum("AVAILABLE", "SOLD", "PENDING", name="propertystatus")

    if is_postgres:
        propertytype.create(bind, checkfirst=True)
        propertystatus.create(bind, checkfirst=True)

    op.create_table('email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_otps_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_otps_purpose'), ['purpose'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('agree_to_terms', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('days_in_week', sa.Integer(), nullable=True),
    sa.Column('time_in_day', sa.String(length=50), nullable=True),
    sa.Column('workout_duration', sa.Integer(), nullable=True),
    sa.Column('refer_photo', sa.String(length=255), nullable=True),
    sa.Column('target_bmi', sa.Float(), nullable=True),
    sa.Column('target_body_fat', sa.Float(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('property_type', propertytype, nullable=False),
    sa.Column('status', propertystatus, nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_title'), ['title'], unique=False)

    op.create_table('property_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_property_favorites_user_property')
    )
    with op.batch_alter_table('property_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_favorites_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    propertytype = sa.Enum("LAND", "HOUSE", "APARTMENT", "COMMERCIAL", name="propertytype")
    propertystatus = sa.Enum("AVAILABLE", "SOLD", "PENDING", name="propertystatus")

    with op.batch_alter_table('property_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_property_favorites_property_id'))

    op.drop_table('property_favorites')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_title'))
        batch_op.drop_index(batch_op.f('ix_properties_id'))

    op.drop_table('properties')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_otps_purpose'))
        batch_op.drop_index(batch_op.f('ix_email_otps_email'))

    op.drop_table('email_otps')

    if is_postgres:
        propertystatus.drop(bind, checkfirst=True)
        propertytype.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
